name: Automation Exercise

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install spell check
        run: pip install black
      - name: Run spell check
        run: black --check .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: pip install pytest coverage numpy matplotlib
      - name: Run coverage
        run: coverage run -m pytest .
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          path: .coverage
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true
